name: code-style

on: [push, pull_request]

jobs:
  pint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4

      - name: Check code style (Pint)
        run: vendor/bin/pint --test
